import assert from "node:assert/strict";
import { mkdtemp, mkdir, readFile, rm, writeFile } from "node:fs/promises";
import os from "node:os";
import path from "node:path";
import test from "node:test";
import { createExhibitionsEditorDraft, validateExhibitionsEditorDraft } from "./exhibitions-draft-state.ts";
import { createExhibitionsPreviewModel } from "./exhibitions-preview.ts";
import { saveExhibitionsEditorDraft } from "./exhibitions-save.ts";
import { serializeExhibitionsEditorDraft } from "./exhibitions-serializer.ts";
import { readExhibitionsEditorEntry, readExhibitionsEditorState } from "./exhibitions-state.ts";

async function fixture(){const root=await mkdtemp(path.join(os.tmpdir(),"exhibitions-editor-")),unit=path.join(root,"test-exhibition");await mkdir(unit);await writeFile(path.join(unit,"index.yaml"),"artists:\n  - artist-one\nstart_date: 2026-08-01\nend_date: 2026-08-10\nopening_hours:\n  opens: 13:00\n  closes: 17:00\nclosed_weekdays:\n  - wed\n  - thu\nhero:\n  image: /test.jpg\n  orientation: landscape\n");await writeFile(path.join(unit,"ja.md"),"---\ntitle: Test Exhibition\nhero_alt: Installation view\n---\nBody copy.\n");await writeFile(path.join(unit,"en.md"),"---\ntitle: __TODO_EN_TITLE__\nhero_alt: __TODO_EN_HERO_ALT__\n---\n");return root;}
test("loads exact three-file state and preserves clean bytes",async()=>{const root=await fixture();try{const state=await readExhibitionsEditorState(root);assert.equal(state.entries.length,1);const draft=createExhibitionsEditorDraft(await readExhibitionsEditorEntry("test-exhibition",root));const files=serializeExhibitionsEditorDraft(draft);assert.equal(files["index.yaml"],await readFile(path.join(root,"test-exhibition/index.yaml"),"utf8"));}finally{await rm(root,{recursive:true});}});
test("JA preview is independent while placeholder EN is blocked",async()=>{const root=await fixture();try{const draft=createExhibitionsEditorDraft(await readExhibitionsEditorEntry("test-exhibition",root));const validation=validateExhibitionsEditorDraft(draft);assert.equal(validation.capabilities.save,true);assert.deepEqual(validation.capabilities.preview,{ja:true,en:false});const preview=createExhibitionsPreviewModel(draft,"ja");assert.equal(preview.localized.title,"Test Exhibition");assert.equal(preview.body,"Body copy.\n");assert.equal("summary" in preview.localized,false);}finally{await rm(root,{recursive:true});}});
test("EN preview carries its own Markdown body without an Exhibition Summary",async()=>{const root=await fixture();try{const draft=createExhibitionsEditorDraft(await readExhibitionsEditorEntry("test-exhibition",root));if(draft.locales.en.state!=="editable")assert.fail();draft.locales.en.value.title="English Exhibition";draft.locales.en.value.hero_alt="English installation view";draft.locales.en.value.body="English body copy.";const preview=createExhibitionsPreviewModel(draft,"en");assert.equal(preview.body,"English body copy.");assert.equal(preview.localized.title,"English Exhibition");assert.equal("summary" in preview.localized,false);}finally{await rm(root,{recursive:true});}});
test("Save atomically updates the selected locale and rereads all files",async()=>{const root=await fixture();try{const baseline=createExhibitionsEditorDraft(await readExhibitionsEditorEntry("test-exhibition",root));const draft=structuredClone(baseline);if(draft.locales.ja.state!=="editable")assert.fail();draft.locales.ja.value.title="Changed";const saved=await saveExhibitionsEditorDraft(draft,baseline,root);assert.equal(saved.locales.ja.state,"editable");assert.match(await readFile(path.join(root,"test-exhibition/ja.md"),"utf8"),/title: Changed/);}finally{await rm(root,{recursive:true});}});
test("Save preserves localized SEO metadata and rereads all files",async()=>{const root=await fixture();try{const baseline=createExhibitionsEditorDraft(await readExhibitionsEditorEntry("test-exhibition",root));const draft=structuredClone(baseline);if(draft.locales.ja.state!=="editable"||draft.locales.en.state!=="editable")assert.fail();draft.locales.ja.value.seo_title="JA SEO title";draft.locales.ja.value.description="JA SEO description";draft.locales.en.value.seo_title="EN SEO title";draft.locales.en.value.description="EN SEO description";const beforeValidation=validateExhibitionsEditorDraft(draft);const saved=await saveExhibitionsEditorDraft(draft,baseline,root);assert.equal(saved.locales.ja.state,"editable");assert.equal(saved.locales.en.state,"editable");if(saved.locales.ja.state!=="editable"||saved.locales.en.state!=="editable")assert.fail();assert.equal(saved.locales.ja.value.seo_title,"JA SEO title");assert.equal(saved.locales.ja.value.description,"JA SEO description");assert.equal(saved.locales.en.value.seo_title,"EN SEO title");assert.equal(saved.locales.en.value.description,"EN SEO description");assert.deepEqual(validateExhibitionsEditorDraft(saved).capabilities,beforeValidation.capabilities);assert.match(await readFile(path.join(root,"test-exhibition/ja.md"),"utf8"),/seo_title: JA SEO title/);assert.match(await readFile(path.join(root,"test-exhibition/en.md"),"utf8"),/seo_title: EN SEO title/);}finally{await rm(root,{recursive:true});}});
test("Shared schedule edits round-trip while localized files never own schedule",async()=>{const root=await fixture();try{const baseline=createExhibitionsEditorDraft(await readExhibitionsEditorEntry("test-exhibition",root));const draft=structuredClone(baseline);if(draft.shared.state!=="editable")assert.fail();draft.shared.value.opening_hours={opens:"12:30",closes:"18:00"};draft.shared.value.closed_weekdays=["mon","fri"];
const saved=await saveExhibitionsEditorDraft(draft,baseline,root);if(saved.shared.state!=="editable")assert.fail();assert.deepEqual(saved.shared.value.opening_hours,{opens:"12:30",closes:"18:00"});assert.deepEqual(saved.shared.value.closed_weekdays,["mon","fri"]);assert.match(await readFile(path.join(root,"test-exhibition/index.yaml"),"utf8"),/opens: 12:30[\s\S]*closes: 18:00[\s\S]*closed_weekdays:\n  - mon\n  - fri/);assert.doesNotMatch(await readFile(path.join(root,"test-exhibition/ja.md"),"utf8"),/opening_hours|closed_days|closed_weekdays/);assert.doesNotMatch(await readFile(path.join(root,"test-exhibition/en.md"),"utf8"),/opening_hours|closed_days|closed_weekdays/);}finally{await rm(root,{recursive:true});}});
test("Exhibitions Editor exposes one Markdown-backed text field and no Summary field",async()=>{const form=await readFile(path.resolve("src/components/editor/ExhibitionsDraftForm.astro"),"utf8");assert.doesNotMatch(form,/name={`\$\{locale\}\.summary`}/);assert.match(form,/Exhibition text/);assert.match(form,/Markdown supported/);assert.match(form,/name={`\$\{locale\}\.body`}/);});
