import { randomUUID } from "node:crypto";
import { promises as fs } from "node:fs";
import path from "node:path";
import { loadExhibitionUnit } from "../content-loaders/exhibitions/repository.ts";
import { isContentId } from "./content-id.ts";
import { createExhibitionsEditorDraft, validateExhibitionsEditorDraft, type ExhibitionsEditorDraftState } from "./exhibitions-draft-state.ts";
import { serializeExhibitionsEditorDraft } from "./exhibitions-serializer.ts";
import { readExhibitionsEditorEntry } from "./exhibitions-state.ts";
const names=["index.yaml","ja.md","en.md"] as const; const canonicalRoot=path.resolve("src/content/exhibitions");
export class ExhibitionsCreateError extends Error { readonly code: "invalid-content-id"|"invalid-draft"|"content-id-collision"|"unsafe-exhibitions-root"|"canonical-mismatch"|"exhibitions-create-rollback-failed"|"create-failed"; constructor(message:string,code:ExhibitionsCreateError["code"],options?:ErrorOptions){super(message,options);this.code=code;} }
export type ExhibitionsCreateFileSystem=Pick<typeof fs,"lstat"|"mkdir"|"readFile"|"readdir"|"rename"|"rm"|"writeFile">;
async function absent(id:string,root:string,io:ExhibitionsCreateFileSystem){if(!isContentId(id))throw new ExhibitionsCreateError("Invalid Content ID","invalid-content-id");const resolved=path.resolve(root),stat=await io.lstat(resolved).catch(()=>undefined);if(!stat?.isDirectory()||stat.isSymbolicLink())throw new ExhibitionsCreateError("Unsafe root","unsafe-exhibitions-root");const dest=path.resolve(resolved,id);if(path.dirname(dest)!==resolved)throw new ExhibitionsCreateError("Invalid Content ID","invalid-content-id");if((await io.readdir(resolved)).some(name=>name.toLowerCase()===id.toLowerCase()||name.toLowerCase()===`${id}.md`))throw new ExhibitionsCreateError("Content ID exists","content-id-collision");return dest;}
export async function createExhibitionsThreeFileEntry(draft:ExhibitionsEditorDraftState,root=canonicalRoot,io:ExhibitionsCreateFileSystem=fs){if(!validateExhibitionsEditorDraft(draft).capabilities.save)throw new ExhibitionsCreateError("Invalid draft","invalid-draft");const dest=await absent(draft.contentId,root,io),output=serializeExhibitionsEditorDraft(draft),stageRoot=path.join(path.resolve(root),`.exhibitions-create-${randomUUID()}`),stage=path.join(stageRoot,draft.contentId);let committed=false;try{await io.mkdir(stageRoot);await io.mkdir(stage);for(const name of names)await io.writeFile(path.join(stage,name),output[name],{flag:"wx"});const unit=await loadExhibitionUnit(stage);if(unit.shared.state!=="valid"||unit.locales.ja.state!=="valid"||unit.locales.en.state!=="valid")throw new ExhibitionsCreateError("Serialized unit invalid","canonical-mismatch");await absent(draft.contentId,root,io);await io.rename(stage,dest);committed=true;return createExhibitionsEditorDraft(await readExhibitionsEditorEntry(draft.contentId,root));}catch(error){if(committed)try{for(const name of names)if(await io.readFile(path.join(dest,name),"utf8")!==output[name])throw new Error("created bytes changed");await io.rm(dest,{recursive:true,force:false});}catch(rollback){throw new ExhibitionsCreateError("Rollback failed","exhibitions-create-rollback-failed",{cause:new AggregateError([error,rollback])});}if(error instanceof ExhibitionsCreateError)throw error;throw new ExhibitionsCreateError("Create failed","create-failed",{cause:error});}finally{await io.rm(stageRoot,{recursive:true,force:true}).catch(()=>{});}}
