import { promises as fs } from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";
import { parseDocument } from "yaml";
import {
  ARTIST_MIGRATION_INVENTORY,
  artistMigrationSha256,
  serializeArtistMigrationManifest,
  type GeneratedArtistMigrationFile,
  type LegacyArtistMigrationItem,
  type LegacyArtistMigrationManifest,
} from "./migration-manifest.ts";
import {
  artistIdentitySchema,
  historicalArtistLocalizedSchema,
} from "./schema.ts";

export const FROZEN_ARTISTS_MIGRATION_MANIFEST_SHA256 =
  "6618fb544aeb3bb6b75b2904ebf734aba7ea066ad0fa03f62b9d2e7acdb42cde";

const RECOVERY_EVIDENCE_FILE = ".artists-migration-recovery.json";
const GENERATED_FILES = [
  ["shared", "index.yaml"],
  ["ja", "ja.md"],
  ["en", "en.md"],
] as const;

export type ArtistMigrationHooks = {
  beforeStagedWrite?: (
    contentId: string,
    filename: string,
  ) => void | Promise<void>;
  afterDirectoryInstalled?: (
    contentId: string,
    directory: string,
  ) => void | Promise<void>;
  beforeSourceRemoval?: (
    contentId: string,
    source: string,
  ) => void | Promise<void>;
  beforeRollbackDirectoryRemoval?: (
    contentId: string,
    directory: string,
  ) => void | Promise<void>;
  beforeRollbackSourceRestore?: (
    contentId: string,
    source: string,
  ) => void | Promise<void>;
};

export type ArtistMigrationOptions = {
  dryRun?: boolean;
  rootOverride?: string;
  hooks?: ArtistMigrationHooks;
};

export type ArtistMigrationResult = {
  migrationVersion: 1;
  transaction: "all-five-global-rollback";
  mode: "dry-run" | "executed";
  contentIds: string[];
  createdDirectories: string[];
  removedSources: string[];
};

export type ArtistMigrationRecoveryEvidence = {
  version: 1;
  collection: "artists";
  status: "manual-recovery-required";
  manifestSha256: string;
  root: string;
  stagingRoot: string;
  originalError: string;
  rollbackErrors: string[];
  installedDirectories: string[];
  removedSources: string[];
  recovery: Array<{
    contentId: string;
    source: string;
    target: string;
    originalBase64: string;
    originalByteLength: number;
    originalSha256: string;
  }>;
};

export class ArtistMigrationManualRecoveryError extends Error {
  readonly evidencePath: string;
  readonly cause: unknown;

  constructor(message: string, evidencePath: string, cause: unknown) {
    super(message);
    this.name = "ArtistMigrationManualRecoveryError";
    this.evidencePath = evidencePath;
    this.cause = cause;
  }
}

function errorMessage(error: unknown): string {
  return error instanceof Error ? error.message : String(error);
}

async function lstatOptional(candidate: string) {
  try {
    return await fs.lstat(candidate);
  } catch (error) {
    if ((error as NodeJS.ErrnoException).code === "ENOENT") return undefined;
    throw error;
  }
}

function assertExactLogicalPath(
  actual: string,
  expected: string,
  label: string,
) {
  if (path.normalize(actual) !== path.normalize(expected))
    throw new Error(`${label} path does not match frozen manifest layout`);
}

function verifyGeneratedEvidence(
  contentId: string,
  generated: GeneratedArtistMigrationFile,
) {
  if (
    Buffer.byteLength(generated.content) !== generated.byteLength ||
    artistMigrationSha256(generated.content) !== generated.sha256
  )
    throw new Error(
      `${contentId}: generated bytes do not match frozen manifest evidence`,
    );
}

function parseMarkdownFrontmatter(content: string, label: string) {
  const match = /^---\n([\s\S]*?)\n---\n$/.exec(content);
  if (!match) throw new Error(`${label}: generated locale file is malformed`);
  const document = parseDocument(match[1], { strict: true, uniqueKeys: true });
  if (document.errors.length)
    throw new Error(`${label}: ${document.errors[0].message}`);
  return document.toJS() as unknown;
}

function validateGeneratedSchemas(entry: LegacyArtistMigrationItem) {
  const sharedDocument = parseDocument(entry.generated.shared.content, {
    strict: true,
    uniqueKeys: true,
  });
  if (sharedDocument.errors.length)
    throw new Error(`${entry.contentId}: generated index.yaml is malformed`);
  if (!artistIdentitySchema.safeParse(sharedDocument.toJS()).success)
    throw new Error(`${entry.contentId}: generated identity schema is invalid`);
  for (const locale of ["ja", "en"] as const) {
    const data = parseMarkdownFrontmatter(
      entry.generated[locale].content,
      `${entry.contentId}/${locale}.md`,
    );
    if (!historicalArtistLocalizedSchema.safeParse(data).success)
      throw new Error(
        `${entry.contentId}: generated ${locale} schema is invalid`,
      );
  }
}

function assertFrozenManifest(manifest: LegacyArtistMigrationManifest) {
  if (
    manifest.migrationVersion !== 1 ||
    manifest.collection !== "artists" ||
    manifest.mode !== "dry-run" ||
    manifest.count !== 5 ||
    manifest.entries.length !== 5 ||
    JSON.stringify(manifest.expectedInventory) !==
      JSON.stringify(ARTIST_MIGRATION_INVENTORY) ||
    artistMigrationSha256(serializeArtistMigrationManifest(manifest)) !==
      FROZEN_ARTISTS_MIGRATION_MANIFEST_SHA256
  )
    throw new Error("Artists migration input is not the frozen manifest");
}

function physicalPaths(
  entry: LegacyArtistMigrationItem,
  root: string,
): { source: string; target: string } {
  return {
    source: path.join(root, `${entry.contentId}.md`),
    target: path.join(root, entry.contentId),
  };
}

async function verifySource(entry: LegacyArtistMigrationItem, source: string) {
  const sourceStat = await lstatOptional(source);
  if (!sourceStat) throw new Error(`${entry.contentId}: source is missing`);
  if (sourceStat.isSymbolicLink() || !sourceStat.isFile())
    throw new Error(`${entry.contentId}: source is not a regular file`);
  const bytes = await fs.readFile(source);
  if (
    bytes.byteLength !== entry.source.byteLength ||
    artistMigrationSha256(bytes) !== entry.source.sha256
  )
    throw new Error(`${entry.contentId}: source drift detected`);
  if (
    entry.source.originalBase64 !== entry.rollback.originalBase64 ||
    entry.source.byteLength !== entry.rollback.originalByteLength ||
    entry.source.sha256 !== entry.rollback.originalSha256 ||
    !bytes.equals(Buffer.from(entry.rollback.originalBase64, "base64"))
  )
    throw new Error(`${entry.contentId}: rollback evidence is inconsistent`);
}

async function verifyInventory(root: string) {
  const rootStat = await fs.lstat(root);
  if (rootStat.isSymbolicLink() || !rootStat.isDirectory())
    throw new Error("Artists source root is not a safe directory");
  const entries = await fs.readdir(root, { withFileTypes: true });
  const markdownNames = entries
    .filter((entry) => entry.name.endsWith(".md"))
    .map((entry) => entry.name)
    .sort();
  const expected = ARTIST_MIGRATION_INVENTORY.map(
    (contentId) => `${contentId}.md`,
  );
  if (JSON.stringify(markdownNames) !== JSON.stringify(expected))
    throw new Error(
      `Unexpected Artists inventory: expected ${expected.join(", ")}; got ${markdownNames.join(", ")}`,
    );
}

async function preflight(
  manifest: LegacyArtistMigrationManifest,
  root: string,
) {
  assertFrozenManifest(manifest);
  await verifyInventory(root);
  if (await lstatOptional(path.join(root, RECOVERY_EVIDENCE_FILE)))
    throw new Error("Artists migration has unresolved recovery evidence");
  const logicalRoot = manifest.sourceRoot;
  const seen = new Set<string>();
  for (const entry of manifest.entries) {
    if (seen.has(entry.contentId))
      throw new Error(`${entry.contentId}: duplicate manifest Content ID`);
    seen.add(entry.contentId);
    if (!ARTIST_MIGRATION_INVENTORY.includes(entry.contentId as never))
      throw new Error(`${entry.contentId}: unexpected manifest Content ID`);
    const logicalSource = path.posix.join(logicalRoot, `${entry.contentId}.md`);
    const logicalTarget = path.posix.join(logicalRoot, entry.contentId);
    assertExactLogicalPath(
      entry.source.path,
      logicalSource,
      `${entry.contentId}: source`,
    );
    assertExactLogicalPath(
      entry.rollback.sourcePath,
      logicalSource,
      `${entry.contentId}: rollback source`,
    );
    assertExactLogicalPath(
      entry.targetDirectory,
      logicalTarget,
      `${entry.contentId}: target`,
    );
    if (
      entry.referenceIdentity.externalId !== entry.contentId ||
      entry.referenceIdentity.localizedEntryIdsAreExternal !== false ||
      entry.referenceIdentity.referenceRewriteRequired !== false
    )
      throw new Error(
        `${entry.contentId}: reference identity evidence changed`,
      );
    for (const [key, filename] of GENERATED_FILES) {
      assertExactLogicalPath(
        entry.generated[key].path,
        path.posix.join(logicalTarget, filename),
        `${entry.contentId}: generated ${key}`,
      );
      verifyGeneratedEvidence(entry.contentId, entry.generated[key]);
    }
    validateGeneratedSchemas(entry);
    const physical = physicalPaths(entry, root);
    await verifySource(entry, physical.source);
    const targetStat = await lstatOptional(physical.target);
    if (targetStat)
      throw new Error(`${entry.contentId}: target collision or unsafe target`);
  }
}

async function verifyWrittenFile(
  contentId: string,
  file: string,
  expected: GeneratedArtistMigrationFile,
) {
  const stat = await fs.lstat(file);
  if (stat.isSymbolicLink() || !stat.isFile())
    throw new Error(`${contentId}: written file is not regular: ${file}`);
  const bytes = await fs.readFile(file);
  if (
    bytes.byteLength !== expected.byteLength ||
    artistMigrationSha256(bytes) !== expected.sha256
  )
    throw new Error(`${contentId}: written file reread mismatch: ${file}`);
}

async function verifyInstalledUnit(
  entry: LegacyArtistMigrationItem,
  directory: string,
) {
  const stat = await fs.lstat(directory);
  if (stat.isSymbolicLink() || !stat.isDirectory())
    throw new Error(`${entry.contentId}: installed target is unsafe`);
  const names = (await fs.readdir(directory)).sort();
  if (
    JSON.stringify(names) !== JSON.stringify(["en.md", "index.yaml", "ja.md"])
  )
    throw new Error(`${entry.contentId}: installed file inventory mismatch`);
  for (const [key, filename] of GENERATED_FILES)
    await verifyWrittenFile(
      entry.contentId,
      path.join(directory, filename),
      entry.generated[key],
    );
  const ja = parseMarkdownFrontmatter(
    entry.generated.ja.content,
    `${entry.contentId}/ja.md`,
  ) as Record<string, unknown>;
  const en = parseMarkdownFrontmatter(
    entry.generated.en.content,
    `${entry.contentId}/en.md`,
  ) as Record<string, unknown>;
  const hasPlaceholder = (data: Record<string, unknown>) =>
    Object.values(data).some(
      (value) => typeof value === "string" && value.includes("__TODO_"),
    );
  if (hasPlaceholder(ja) || !hasPlaceholder(en))
    throw new Error(`${entry.contentId}: installed unit validation failed`);
}

async function restoreSourceFromEvidence(
  entry: LegacyArtistMigrationItem,
  source: string,
) {
  const expected = Buffer.from(entry.rollback.originalBase64, "base64");
  if (
    expected.byteLength !== entry.rollback.originalByteLength ||
    artistMigrationSha256(expected) !== entry.rollback.originalSha256
  )
    throw new Error(`${entry.contentId}: rollback bytes are invalid`);
  const existing = await lstatOptional(source);
  if (existing) {
    if (existing.isSymbolicLink() || !existing.isFile())
      throw new Error(`${entry.contentId}: rollback source path is unsafe`);
    const current = await fs.readFile(source);
    if (!current.equals(expected))
      throw new Error(`${entry.contentId}: rollback source path is occupied`);
    return;
  }
  const temporary = `${source}.artists-rollback`;
  await fs.writeFile(temporary, expected, { flag: "wx" });
  const reread = await fs.readFile(temporary);
  if (!reread.equals(expected))
    throw new Error(`${entry.contentId}: rollback source reread failed`);
  await fs.rename(temporary, source);
}

async function persistRecoveryEvidence(
  manifest: LegacyArtistMigrationManifest,
  root: string,
  stagingRoot: string,
  originalError: unknown,
  rollbackErrors: string[],
  installedDirectories: string[],
  removedSources: string[],
) {
  const evidence: ArtistMigrationRecoveryEvidence = {
    version: 1,
    collection: "artists",
    status: "manual-recovery-required",
    manifestSha256: FROZEN_ARTISTS_MIGRATION_MANIFEST_SHA256,
    root,
    stagingRoot,
    originalError: errorMessage(originalError),
    rollbackErrors,
    installedDirectories,
    removedSources,
    recovery: manifest.entries.map((entry) => {
      const physical = physicalPaths(entry, root);
      return {
        contentId: entry.contentId,
        source: physical.source,
        target: physical.target,
        originalBase64: entry.rollback.originalBase64,
        originalByteLength: entry.rollback.originalByteLength,
        originalSha256: entry.rollback.originalSha256,
      };
    }),
  };
  const evidencePath = path.join(root, RECOVERY_EVIDENCE_FILE);
  await fs.writeFile(evidencePath, `${JSON.stringify(evidence, null, 2)}\n`, {
    flag: "wx",
  });
  return evidencePath;
}

export async function executeLegacyArtistMigration(
  manifest: LegacyArtistMigrationManifest,
  options: ArtistMigrationOptions = {},
): Promise<ArtistMigrationResult> {
  const root = path.resolve(options.rootOverride ?? manifest.sourceRoot);
  await preflight(manifest, root);
  const contentIds = manifest.entries.map((entry) => entry.contentId);
  if (options.dryRun)
    return {
      migrationVersion: 1,
      transaction: "all-five-global-rollback",
      mode: "dry-run",
      contentIds,
      createdDirectories: [],
      removedSources: [],
    };

  const stagingRoot = await fs.mkdtemp(
    path.join(root, ".artists-migration-stage-"),
  );
  const stagedRoot = path.join(stagingRoot, "generated");
  const removedRoot = path.join(stagingRoot, "removed-sources");
  const installed: Array<{ contentId: string; directory: string }> = [];
  const removed: Array<{ contentId: string; source: string }> = [];
  let cleanupStaging = true;
  try {
    await fs.mkdir(stagedRoot);
    await fs.mkdir(removedRoot);
    for (const entry of manifest.entries) {
      const directory = path.join(stagedRoot, entry.contentId);
      await fs.mkdir(directory);
      for (const [key, filename] of GENERATED_FILES) {
        await options.hooks?.beforeStagedWrite?.(entry.contentId, filename);
        await fs.writeFile(
          path.join(directory, filename),
          entry.generated[key].content,
          { flag: "wx" },
        );
      }
      await verifyInstalledUnit(entry, directory);
    }

    for (const entry of manifest.entries) {
      const target = physicalPaths(entry, root).target;
      if (await lstatOptional(target))
        throw new Error(
          `${entry.contentId}: target appeared after migration preflight`,
        );
      await fs.rename(path.join(stagedRoot, entry.contentId), target);
      installed.push({ contentId: entry.contentId, directory: target });
      await options.hooks?.afterDirectoryInstalled?.(entry.contentId, target);
    }
    for (const entry of manifest.entries)
      await verifyInstalledUnit(entry, physicalPaths(entry, root).target);
    await verifyInventory(root);

    for (const entry of manifest.entries) {
      const source = physicalPaths(entry, root).source;
      await verifySource(entry, source);
      await options.hooks?.beforeSourceRemoval?.(entry.contentId, source);
      await fs.rename(source, path.join(removedRoot, `${entry.contentId}.md`));
      removed.push({ contentId: entry.contentId, source });
    }
    for (const entry of manifest.entries) {
      const { source, target } = physicalPaths(entry, root);
      if (await lstatOptional(source))
        throw new Error(`${entry.contentId}: legacy source removal failed`);
      await verifyInstalledUnit(entry, target);
    }

    await fs.rm(stagingRoot, { recursive: true });
    cleanupStaging = false;

    return {
      migrationVersion: 1,
      transaction: "all-five-global-rollback",
      mode: "executed",
      contentIds,
      createdDirectories: installed.map((item) => item.directory),
      removedSources: removed.map((item) => item.source),
    };
  } catch (error) {
    const rollbackErrors: string[] = [];
    for (const item of [...installed].reverse()) {
      try {
        await options.hooks?.beforeRollbackDirectoryRemoval?.(
          item.contentId,
          item.directory,
        );
        const stat = await lstatOptional(item.directory);
        if (stat) {
          if (stat.isSymbolicLink() || !stat.isDirectory())
            throw new Error(`${item.contentId}: rollback target is unsafe`);
          await fs.rm(item.directory, { recursive: true });
        }
      } catch (rollbackError) {
        rollbackErrors.push(errorMessage(rollbackError));
      }
    }
    for (const entry of manifest.entries) {
      const source = physicalPaths(entry, root).source;
      try {
        await options.hooks?.beforeRollbackSourceRestore?.(
          entry.contentId,
          source,
        );
        await restoreSourceFromEvidence(entry, source);
      } catch (rollbackError) {
        rollbackErrors.push(errorMessage(rollbackError));
      }
    }
    if (rollbackErrors.length === 0) {
      try {
        await fs.rm(stagingRoot, { recursive: true });
        cleanupStaging = false;
      } catch (rollbackError) {
        rollbackErrors.push(errorMessage(rollbackError));
      }
    }
    if (rollbackErrors.length) {
      cleanupStaging = false;
      const evidencePath = await persistRecoveryEvidence(
        manifest,
        root,
        stagingRoot,
        error,
        rollbackErrors,
        installed.map((item) => item.directory),
        removed.map((item) => item.source),
      );
      throw new ArtistMigrationManualRecoveryError(
        `Artists migration rollback failed; recovery evidence: ${evidencePath}`,
        evidencePath,
        error,
      );
    }
    throw error;
  } finally {
    if (cleanupStaging)
      await fs.rm(stagingRoot, { recursive: true, force: true });
  }
}

const isCli =
  process.argv[1] &&
  fileURLToPath(import.meta.url) === path.resolve(process.argv[1]);
if (isCli) {
  const args = process.argv.slice(2);
  const manifestFile = args.find((argument) => !argument.startsWith("--"));
  if (!manifestFile)
    throw new Error(
      "Usage: artists:migration:execute <frozen-manifest.json> --dry-run|--execute",
    );
  const dryRun = args.includes("--dry-run");
  const execute = args.includes("--execute");
  if (dryRun === execute)
    throw new Error("Choose exactly one of --dry-run or --execute");
  const manifest = JSON.parse(
    await fs.readFile(path.resolve(manifestFile), "utf8"),
  ) as LegacyArtistMigrationManifest;
  const result = await executeLegacyArtistMigration(manifest, { dryRun });
  process.stdout.write(`${JSON.stringify(result, null, 2)}\n`);
}
